select * from createOrganization('CIMMYT','','http://www.cimmyt.org',1,NULL,NULL,NULL,1);
select * from createOrganization('Diversity Arrays Technology','','',1,NULL,NULL,NULL,1);
select * from createOrganization('SAGA','','http://www.cimmyt.org',1,NULL,NULL,NULL,1);
select * from createOrganization('Genomic Diversity Facility, Cornell University','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Cornell University','','',1,NULL,NULL,NULL,1);
select * from createOrganization('LGC Genomics Ltd','','',1,NULL,NULL,NULL,1);
select * from createOrganization('CIMMYT Maize Molecular Breeding Laboratory','','http://www.cimmyt.org',1,NULL,NULL,NULL,1);
select * from createOrganization('Illumina Inc.','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Cornell University - GOBII project','Ithaca; NY; USA','http://cbsugobii05.tc.cornell.edu/wordpress/',1,NULL,NULL,NULL,1);
select * from createContact('Olsen','Michael','contact_3','m.olsen@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Zhang','Xuecai','contact_4','XC.Zhang@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Hearne','Sarah','contact_5','s.hearne@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Nair','Sudha','contact_6','sudha.nair@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Semagn','Kassa','contact_7','CIMMYT-DMU@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Raman','Babu','contact_8','CIMMYT-DMU@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Gowda','Manje','contact_9','m.gowda@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Huestis','Gordon','contact_10','g.huestis@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Magorokosho','Cosmos','contact_11','C.Magorokosho@CGIAR.ORG','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Beyene','Yoseph','contact_12','Y.Beyene@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Chen','Jiafa','contact_13','JF.chen@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Molnar','Terence','contact_14','t.molnar@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Jumbo','Bright','contact_15','b.jumbo@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Briones','Ernesto','contact_16','e.briones@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Dhliwayo','Thanda','contact_17','D.Thanda@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Dhugga','Kanwarpal','contact_18','k.dhugga@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Makumbi','Dan','contact_19','d.makumbi@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('San Vicente','Feliz','contact_20','f.sanvicente@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Puebla','Luis','contact_21','l.puebla@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Riis','Jens','contact_22','j.riis@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Pixley','Kevin','contact_23','k.pixley@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Zaidi','P.H.','contact_24','phzaidi@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Vivek','Bindiganavile','contact_25','b.vivek@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Boddupalli','Prasanna','contact_26','b.m.prasanna@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Banziger','Marianne','contact_27','m.banziger@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Campos','Jaime','contact_28','J.A.Campos@cgiar.org','{3}',1,NULL,NULL,NULL,1);
select * from createContact('Ayala','Claudio','contact_29','c.ayala@cgiar.org','{1,3}',1,NULL,NULL,NULL,1);
select * from createContact('Shrestha','Rosemary','contact_30','R.Shrestha2@cgiar.org','{3}',1,NULL,NULL,NULL,1);
select * from createContact('Ulat','Victor','contact_31','v.ulat@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Diversity Arrays Technology','Australia','contact_32','andrzej@diversityarrays.com','{4}',1,NULL,NULL,NULL,2);
select * from createContact('SAGA','Servicio de Análisis Genético para la Agricultura','contact_33','c.sansaloni@cgiar.org','{4}',1,NULL,NULL,NULL,3);
select * from createContact('Genomic Diversity Facility','Cornell University','contact_34','BRC_genomic-diversity@cornell.edu','{4}',1,NULL,NULL,NULL,4);
select * from createContact('Institute for Genomic Diversity','Cornell University','contact_35','sem30@cornell.edu','{4}',1,NULL,NULL,NULL,5);
select * from createContact('LGC','Genomics','contact_36','info@lgcgroup.com','{4}',1,NULL,NULL,NULL,6);
select * from createContact('CIMMYT','Maize Molecular Breeding Laboratory','contact_37','g.huestis@cgiar.org','{4}',1,NULL,NULL,NULL,7);
select * from createContact('Illumina','Inc.','contact_38','info@illumina.com','{4}',1,NULL,NULL,NULL,8);
select * from createContact('Dreher','Kate','contact_39','k.dreher@cgiar.org','{1,3}',1,NULL,NULL,NULL,1);
select * from createContact('Robbins','Kelly','contact_40','krr73@cornell.edu','{6}',1,NULL,NULL,NULL,9);
select * from createContact('Gao','Star','contact_41','yg28@cornell.edu','{6}',1,NULL,NULL,NULL,9);
select * from createContact('Jones','Liz','contact_42','ej245@cornell.edu','{6}',1,NULL,NULL,NULL,9);