select * from createOrganization('International Rice Research Institute','Pili Drive, UPLB, Los Baños, 4031 Laguna','http://irri.org/',1,NULL,NULL,NULL,1);
select * from createContact('Sheryl','Hechanova','contact_3','s.hechanova@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Tobias','Kretzschmar','contact_4','t.kretzschmar@irri.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('John','Ignacio','contact_5','j.ignacio@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Rafael Julian','Panerio','contact_6','r.panerio@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Kristine Alexis','Arellano','contact_7','k.arellano@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Socorro','Carandang','contact_8','s.carandang@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Annalhea','Jarana','contact_9','a.jarana@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Grace','Carino','contact_10','g.carino@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Geraldine','Layaoen','contact_11','g.malitic@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Geisha','Sanchez','contact_12','g.sanchez@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Krizzel','Llantada','contact_13','k.llantada@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Maria','Dwiyanti','contact_14','m.dwiyanti@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Inez Slamet','Loedin','contact_15','i.slamet-loedin@irri.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Prabhjit','Chadha Mohanty','contact_16','p.chadha-mohanty@irri.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Mylah','Anacleto','contact_17','m.anacleto@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Erwin','Tandayu','contact_18','e.tandayu@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Maria','Reveche','contact_19','m.reveche@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Christine Jade','Ermita','contact_20','c.dilla@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Rolando ','Santos Jr.','contact_21','jay.santos@irri.org','{5}',1,NULL,NULL,NULL,1);
select * from createContact('Roven Rommel ','Fuentes','contact_22','r.fuentes@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('France Nikki','Borja','contact_23','f.borja@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Ramil','Mauleon','contact_24','r.mauleon@irri.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Nickolai','Alexandrov','contact_25','n.alexandrov@irri.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Juan Miguel Carlos','Abriol','contact_26','m.abriol@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Venice Margarette','Juanillas','contact_27','v.juanillas@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Angel Manica ','Raquel','contact_28','a.raquel@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Viana Carla','Calaminos','contact_29','v.calaminos@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Locedie','Mansueto','contact_30','l.mansueto@irri.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Jeffrey','Detras','contact_31','j.detras@irri.org','{3}',1,NULL,NULL,NULL,1);
