select * from createOrganization('International Crops Research Institute for the Semi-Arid Tropics (ICRISAT)','Patancheru 502324, Telangana State, India','http://www.icrisat.org/',1,NULL,NULL,NULL,1);
select * from createOrganization('Affymetrix, Inc., Singapore','','',1,NULL,NULL,NULL,1);
select * from createOrganization('BGI Shenzhen, China','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Genomic Diversity Facility, Cornell University, USA','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Diversity Arrays Technology','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Genotypic Technology, India','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Genotyping Service Laboratory (GSL), Center of Excellence in Genomics (CEG), ICRISAT, India','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Intertek Group plc, Australia','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Intertek Group plc, India','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Intertek Group plc, Sweden','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Intertek Group plc, USA','','',1,NULL,NULL,NULL,1);
select * from createOrganization('LGC Genomics Ltd','UK','',1,NULL,NULL,NULL,1);
select * from createOrganization('Macrogen Korea, Rep. of Korea','','',1,NULL,NULL,NULL,1);
select * from createOrganization('SciGenom, India','','',1,NULL,NULL,NULL,1);
select * from createContact('Bajaj','Prasad','contact_3','p.bajaj@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Das','Roma','contact_4','r.das@cgiar.org','{3}',1,NULL,NULL,NULL,1);
select * from createContact('Despande','Santosh','contact_5','s.deshpande@cgiar.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Gaur','Pooran','contact_6','p.gaur@cgiar.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Grando','Stefania','contact_7','s.grando@cgiar.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Kudapa','Himabindu','contact_8','k.himabindu@cgiar.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Kumar','Are Ashok','contact_9','a.ashokkumar@cgiar.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Rathore','Abhishek','contact_10','a.rathore@cgiar.org','{3}',1,NULL,NULL,NULL,1);
select * from createContact('Roorkiwal','Manish','contact_11','m.roorkiwal@cgiar.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Selvanayagam','Sivasubramani','contact_12','s.sivasubramani@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Varshney','Rajeev','contact_13','r.k.varshney@cgiar.org','{1,6}',1,NULL,NULL,NULL,1);
select * from createContact('Vemula','Anilkumar','contact_14','anil.kumar@cgiar.org','{3}',1,NULL,NULL,NULL,1);
select * from createContact('Affymetrix Inc.','Singapore','contact_15','support@affymetrix.com','{4}',1,NULL,NULL,NULL,2);
select * from createContact('BGI Shenzhen','China','contact_16','info@genomics.cn','{4}',1,NULL,NULL,NULL,3);
select * from createContact('Genomic Diversity Facility','Cornell University','contact_17','BRC_genomic-diversity@cornell.edu','{4}',1,NULL,NULL,NULL,4);
select * from createContact('Diversity Arrays Technology','Australia','contact_18','andrzej@diversityarrays.com','{4}',1,NULL,NULL,NULL,5);
select * from createContact('Genotypic Technology','India','contact_19','genomicsatgenotypic.co.in','{4}',1,NULL,NULL,NULL,6);
select * from createContact('Genotyping Service Laboratory (GSL), Center of Excellence in Genomics (CEG)','ICRISAT, India','contact_20',' t.mahendar@cgiar.org ','{4}',1,NULL,NULL,NULL,7);
select * from createContact('Intertek Group plc','Australia','contact_21','web.apac.aus@intertek.com','{4}',1,NULL,NULL,NULL,8);
select * from createContact('Intertek Group plc','India','contact_22','web.apac.aus@intertek.com','{4}',1,NULL,NULL,NULL,9);
select * from createContact('Intertek Group plc','Sweden','contact_23','sweden@intertek.com','{4}',1,NULL,NULL,NULL,10);
select * from createContact('Intertek Group plc','USA','contact_24','usa@intertek.com','{4}',1,NULL,NULL,NULL,11);
select * from createContact('LGC','Genomics','contact_25','info@lgcgroup.com','{4}',1,NULL,NULL,NULL,12);
select * from createContact('Macrogen Korea','Rep. of Korea','contact_26','info@macrogenla.com.ar','{4}',1,NULL,NULL,NULL,13);
select * from createContact('SciGenom','India','contact_27','info@scigenom.com ','{4}',1,NULL,NULL,NULL,14);