select * from createOrganization('CIMMYT','','www.cimmyt.org',1,NULL,NULL,NULL,1);
select * from createOrganization('ICARDA','','www.icarda.org',1,NULL,NULL,NULL,1);
select * from createOrganization('Diversity Arrays Technology','','',1,NULL,NULL,NULL,1);
select * from createOrganization('SAGA','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Genomic Diversity Facility, Cornell University','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Institute for Genomic Diversity, Cornell University','','',1,NULL,NULL,NULL,1);
select * from createOrganization('LGC Genomics Ltd','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Illumina Inc.','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Kansas State University','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Trait Genetics','','',1,NULL,NULL,NULL,1);
select * from createOrganization('University of Bristol','','',1,NULL,NULL,NULL,1);
select * from createOrganization('CIMMYT Wheat Molecular Breeding Laboratories','','',1,NULL,NULL,NULL,1);
select * from createOrganization('Cornell University - GOBII project','Ithaca; NY; USA','http://cbsugobii05.tc.cornell.edu/wordpress/',1,NULL,NULL,NULL,1);
select * from createContact('Shrestha','Rosemary','contact_3','R.Shrestha2@cgiar.org','{5,3}',1,NULL,NULL,NULL,1);
select * from createContact('Ulat','Victor','contact_4','v.ulat@cgiar.org','{5}',1,NULL,NULL,NULL,1);
select * from createContact('Rutkoski','Jessica','contact_5','j.rutkoski@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Dreisigacker','Susanne','contact_6','s.dreisigacker@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Sansaloni','Carolina','contact_7','c.sansaloni@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Singh','Sukhwinder','contact_8','suk.singh@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Singh','Ravi','contact_9','r.singh@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Ammar','Karim','contact_10','k.ammar@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Sukumaran','Siva','contact_11','s.sukumaran@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Braun','Hans','contact_12','h.j.braun@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Lan','Caixia','contact_13','C.Lan@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Baum','Michael','contact_14','m.baum@cgiar.org','{6}',1,NULL,NULL,NULL,2);
select * from createContact('Reynolds','Matthew','contact_15','M.REYNOLDS@CGIAR.ORG','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Molero','Gemma','contact_16','g.molero@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Sehgal','Deepmala','contact_17','D.Sehgal@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Kishii','Masahiro','contact_18','m.kishii@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Randhawa','Mandeep','contact_19','M.RANDHAWA@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Vikram','Prashant','contact_20','p.vikram@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Campos','Jaime','contact_21','J.A.Campos@cgiar.org','{3}',1,NULL,NULL,NULL,1);
select * from createContact('Banziger','Marianne','contact_22','m.banziger@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Govindan','Velu','contact_23','velu@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Singh','Pawan','contact_24','p.singh@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('He','Xinyao','contact_25','X.He@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Crespo','Leonardo','contact_26','l.crespo@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Basnet','Bhoja','contact_27','B.R.Basnet@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Diversity Arrays Technology','Australia','contact_28','andrzej@diversityarrays.com','{4}',1,NULL,NULL,NULL,3);
select * from createContact('SAGA','Servicio de Análisis Genético para la Agricultura','contact_29','c.sansaloni@cgiar.org','{4}',1,NULL,NULL,NULL,4);
select * from createContact('Genomic Diversity Facility','Cornell University','contact_30','BRC_genomic-diversity@cornell.edu','{4}',1,NULL,NULL,NULL,5);
select * from createContact('Institute for Genomic Diversity','Cornell University','contact_31','sem30@cornell.edu','{4}',1,NULL,NULL,NULL,6);
select * from createContact('LGC','Genomics','contact_32','info@lgcgroup.com','{4}',1,NULL,NULL,NULL,7);
select * from createContact('Illumina','Inc.','contact_33','info@illumina.com','{4}',1,NULL,NULL,NULL,8);
select * from createContact('KSU','Kansas State University','contact_34','jpoland@ksu.edu','{4}',1,NULL,NULL,NULL,9);
select * from createContact('Trait','Genetics','contact_35','ganal@traitgenetics.de','{4}',1,NULL,NULL,NULL,10);
select * from createContact('University of Bristol','Axiom Array','contact_36','simon.griffiths@jic.ac.uk','{4}',1,NULL,NULL,NULL,11);
select * from createContact('CIMMYT','Wheat Molecular Breeding Laboratory','contact_37','s.dreisigacker@cgiar.org','{4}',1,NULL,NULL,NULL,12);
select * from createContact('Dreher','Kate','contact_38','k.dreher@cgiar.org','{5,3}',1,NULL,NULL,NULL,1);
select * from createContact('Olsen','Michael','contact_39','m.olsen@cgiar.org','{1}',1,NULL,NULL,NULL,1);
select * from createContact('Puebla','Luis','contact_40','l.puebla@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Riis','Jens','contact_41','j.riis@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Pixley','Kevin','contact_42','k.pixley@cgiar.org','{6}',1,NULL,NULL,NULL,1);
select * from createContact('Jones','Liz','contact_43','ej245@cornell.edu','{6}',1,NULL,NULL,NULL,13);
select * from createContact('Robbins','Kelly','contact_44','krr73@cornell.edu','{6}',1,NULL,NULL,NULL,13);
select * from createContact('Gao','Star','contact_45','yg28@cornell.edu','{6}',1,NULL,NULL,NULL,13);
