--liquibase formatted sql

--changeset raza:maize_contact_rel context:seed_maize splitStatements:false
 Select * from createcontact('Ulat','Victor','contact_code_Ulat','v.ulat@cgiar.org',( select array_agg(role_id) from role where role_name in ('Admin')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Zhang','Xuecai','contact_code_Zhang','XC.Zhang@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'XC.Zhang@cgiar.org');
 Select * from createcontact('Hearne','Sarah','contact_code_Hearne','s.hearne@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Nair','Sudha','contact_code_Nair','sudha.nair@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Semagn','Kassa','contact_code_Semagn','K.Semagn@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Raman','Babu','contact_code_Raman','r.babu@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Gowda','Manje','contact_code_Gowda','m.gowda@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Huestis','Gordon','contact_code_Huestis','g.huestis@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Magorokosho','Cosmos','contact_code_Magorokosho','C.Magorokosho@CGIAR.ORG',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Beyene','Yoseph','contact_code_Beyene','Y.Beyene@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Chen','Jiafa','contact_code_Chen','JF.chen@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Molnar','Terence','contact_code_Molnar','t.molnar@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Crossa','Jose','contact_code_Crossa','j.crossa@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Burgueno','Juan','contact_code_Burgueno','j.burgueno@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Jumbo','Bright','contact_code_Jumbo','b.jumbo@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Briones','Ernesto','contact_code_Briones','e.briones@cgiar.org',( select array_agg(role_id) from role where role_name in ('Curator')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Dhliwayo','Thanda','contact_code_Dhliwayo','D.Thanda@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Dhugga','Kanwarpal','contact_code_Dhugga','k.dhugga@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Makumbi','Dan','contact_code_Makumbi','d.makumbi@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('San Vicente','Felix','contact_code_San Vicente','f.sanvicente@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Ayala','Claudio','contact_code_Ayala','c.ayala@cgiar.org',( select array_agg(role_id) from role where role_name in ('Curator')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'c.ayala@cgiar.org');
 Select * from createcontact('Ogugo','Veronica','contact_code_Ogugo','V.Ogugo@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Petroli','Cesar','contact_code_Petroli','C.petroli@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Campos','Jaime','contact_code_Campos','J.A.Campos@cgiar.org',( select array_agg(role_id) from role where role_name in ('Admin', 'User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Banziger','Marianne','contact_code_Banziger','m.banziger@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Zaidi','P.H.','contact_code_Zaidi','phzaidi@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Vivek','Bindiganavile','contact_code_Vivek','b.vivek@cgiar.org',( select array_agg(role_id) from role where role_name in ('PI')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Boddupalli','Prasanna','contact_code_Boddupalli','b.m.prasanna@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Ng''ang''a','Maureen','contact_code_Nganga','M.Ng''ang''a@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Shrestha','Rosemary','contact_code_Shrestha','R.Shrestha2@cgiar.org',( select array_agg(role_id) from role where role_name in ('Curator', 'PI', 'User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Dreher','Kate','contact_code_Dreher','k.dreher@cgiar.org',( select array_agg(role_id) from role where role_name in ('Admin', 'Curator', 'PI', 'User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'k.dreher@cgiar.org');
 Select * from createcontact('Olsen','Michael','contact_code_Olsen','m.olsen@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Puebla','Luis','contact_code_Puebla','l.puebla@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Riis','Jens','contact_code_Riis','j.riis@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Pixley','Kevin','contact_code_Pixley','k.pixley@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Jones','Liz','contact_code_Jones','ej245@cornell.edu',( select array_agg(role_id) from role where role_name in ('Curator', 'User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Robbins','Kelly','contact_code_Robbins','krr73@cornell.edu',( select array_agg(role_id) from role where role_name in ('Curator', 'User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Gao','Star','contact_code_Gao','yg28@cornell.edu',( select array_agg(role_id) from role where role_name in ('Curator', 'User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Kropff','Martin','contact_code_Kropff','m.kropff@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Carvalho','Marcela','contact_code_Carvalho','m.carvalho@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');
 Select * from createcontact('Hernandez','Martha','contact_code_Hernandez','i.hernandez@cgiar.org',( select array_agg(role_id) from role where role_name in ('User')),1,current_date,NULL,NULL,(select organization_id from organization where name = 'CIMMYT' ),'');

